### ISSUE TITLE
IDL template uses an unsupported preprocessor directive for connext

### ISSUE THREAD

**Issue by tfoote** [ros2/rosidl_dds#11]
This line https://github.com/ros2/rosidl_dds/blob/0b7c2e797a4688b7e85a5ce8b5bb9c57c97f33c0/rosidl_generator_dds_idl/resource/msg.idl.template#L90

Produces creates warnings for every connext message generated to the effect of: 

```
INFO com.rti.ndds.nddsgen.Main Running rtiddsgen version 2.2.0.0, please wait ...
WARN com.rti.ndds.nddsgen.antlr.auto.IdlLexer ParamDescription_.idl line 33  preprocessor directive not supported. It will be ignored
WARN com.rti.ndds.nddsgen.antlr.auto.IdlLexer Param_.idl line 29  preprocessor directive not supported. It will be ignored
INFO com.rti.ndds.nddsgen.Main Done
Generating: /home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_typesupport_connext_cpp/rcl_interfaces/dds_connext/ParamDescription_.h/cpp
```

**Comment by tfoote** [comment]
We currently run the generator twice, but it doesn't currently know the target at the moment.

**Comment by dirk-thomas** [comment]
The generator is currently (and should stay) vendor agnostic. I will likely need to be extended to support custom modifications of the generated IDL code.

**Comment by wjwwood** [comment]
One idea on how to do that is to have the vendor agnostic generator leave replaceable comments in the generated IDL file. So if you start with:

```
# file: foo_pkg/Foo.msg
int bar
```

Then after the vendor agnostic IDL generator you get something like:

``` c++
// file: generic/foo_pkg/Foo_.idl
#ifndef __foo_pkg__String__h__
#define __foo_pkg__String__h__

// REPLACEME before_namespace

module foo_pkg
{
module dds_
{

// REPLACEME in_namespace_before_struct

struct Foo_
{
  int bar_;
};  // struct Foo_

// REPLACEME in_namespace_after_struct

};  // module dds_

};  // module foo_pkg

// REPLACEME after_namespace

#endif  // __foo_pkg__String__h__
```

This would be the input to each of the vendor specific generators, which would first do any find and replace needed in the generic IDL file, then pass that to their code generator. The Connext specific file would end up looking like this:

``` c++
// file: connext/foo_pkg/Foo_.idl
#ifndef __foo_pkg__String__h__
#define __foo_pkg__String__h__

module foo_pkg
{
module dds_
{

struct Foo_
{
  int bar_;
};  // struct Foo_

};  // module dds_

};  // module foo_pkg

#endif  // __foo_pkg__String__h__
```

And the OpenSplice might look like this:

``` c++
// file: opensplice/foo_pkg/Foo_.idl
#ifndef __foo_pkg__String__h__
#define __foo_pkg__String__h__

module foo_pkg
{
module dds_
{

struct Foo_
{
  int bar_;
};  // struct Foo_

#pragma keylist Foo_

};  // module dds_

};  // module foo_pkg

#endif  // __foo_pkg__String__h__
```

**Comment by dirk-thomas** [comment]
Following the same idea but avoiding multiple replacements the generator could just expose several extension points and if the caller likes to it can provide a template / snippet to be inserted in those extension points.

For both approaches the generator must "foresee" the potential customizations though.

**Comment by wjwwood** [comment]
I suggested my approach because it doesn't require extra CMake infrastructure between generators and if the vendor specific generator does no replacing it should still work since they are comments. I didn't optimize for less replacements because I don't think that they really cost anything.

**Comment by dirk-thomas** [comment]
Extendibility is already part of the infrastructure since it is required for other features of the generators: see https://github.com/ros2/rosidl_dds/blob/7a00a794a5b210be43225332a88ce9cb5dfe2795/rosidl_generator_dds_idl/cmake/rosidl_generate_dds_interfaces.cmake#L30-L31 and https://github.com/ros2/rosidl_dds/blob/7a00a794a5b210be43225332a88ce9cb5dfe2795/rosidl_generator_dds_idl/rosidl_generator_dds_idl/__init__.py#L37-L41

Therefore I have implemented an extension point so that specific generators can provide custom code in the location where the pragma was hard coded before:
- ros2/rosidl_dds#18
- ros2/rmw_opensplice#32
